import jsPDF from "jspdf";

type ProtocolExportData = {
  studyTitle: string;
  hasIntervention: boolean | null;
  populationDescription: string;
  ageMin: string;
  ageMax: string;
  variableType: string;
  measurementScale: string;
  groupStructure: string;
  distribution: string;
};

export function generateProtocolPdf(data: ProtocolExportData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 25;

  const addSectionTitle = (title: string) => {
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 128, 128); // teal, matching your brand color
    doc.text(title, margin, y);
    y += 8;
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  };

  const addField = (label: string, value: string) => {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100, 100, 100);
    doc.text(label, margin, y);
    y += 5;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(20, 20, 20);
    const lines = doc.splitTextToSize(value || "Not provided", pageWidth - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 6 + 6;
  };

  // Title page header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 53, 95); // navy, matching your brand color
  doc.text("Clinical Research Protocol", margin, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated by ProtocolPilot on ${new Date().toLocaleDateString()}`, margin, y);
  y += 14;

  addSectionTitle("Study Overview");
  addField("Study Title", data.studyTitle);

  addSectionTitle("Study Design");
  addField(
    "Intervention Involved",
    data.hasIntervention === null ? "Not answered" : data.hasIntervention ? "Yes" : "No"
  );
  addField(
    "Study Classification",
    data.hasIntervention ? "Interventional (RCT Configuration)" : "Observational (Cohort Strategy)"
  );

  addSectionTitle("Methodology");
  addField("Target Population", data.populationDescription);
  addField("Age Range", `${data.ageMin || "?"} to ${data.ageMax || "?"} years`);

  addSectionTitle("Statistical Plan");
  addField("Variable Type", data.variableType);
  addField("Measurement Scale", data.measurementScale);
  addField("Group Structure", data.groupStructure);
  addField("Distribution", data.distribution);

  doc.save(`${data.studyTitle || "protocol"}-export.pdf`);
}